default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timezone: 'utc'

development:
  <<: *default
  database: praca_inzynierska_development

test:
  <<: *default
  database: praca_inzynierska_test

production:
  <<: *default
  database: praca_inzynierska_production
  username: szymon
  password: <%= ENV["PRACA_INZYNIERSKA_DATABASE_PASSWORD"] %>

staging:
  <<: *default
  database: praca_inzynierska_staging
  username: szymon
  password: <%= ENV["PRACA_INZYNIERSKA_DATABASE_PASSWORD"] %>
